### ISSUE TITLE
Correção Exercício `0.5.1`

### ISSUE THREAD

**Issue by mathiasgheno** [tete-30/0.5.1#1]
# Correção Exercício `0.5.1`

> Considere o wireframe abaixo como um guia visual para um sistema web que faz listagem de tarefas considerando três status: Pendentes, Concluídas e Excluídas.  [Referência visual](https://i.imgur.com/AsfPVcN.jpg). 

Faltou adicionar um estilo em negrito para a página "ativa", assim como o efeito de scale para o quando o mouse do usuário passar por cima da tarefa. 

O primeiro ítem poderia ser obtido com o uso de uma classe extra com efeito de negrito e então a adição dessa classe dentro do arquivo .html que a página está ativa. 

```html
<style>
  .ativo {
    text-weight: bold;
  }
</style>

<a href="pendentes.html" class="ativo pendentes">Pendentes</a>
```

O segundo ítem pode ser obtido através do uso do `:hover` para o seu `p`.

```css
p {
    border-radius: 5px;
    border: 2px solid #8FD14F;
    padding: 7px;
    transition: transform 0.1s ease-in-out;
}

p:hover {
    transform: scale(1.1);
}
```

**Nota:** 8 

# Comentários
Notei que o seu código está muito mal indentado. No VS Code você pode aplicar a formação automaticamente seguindo esses passos:
1. CTRL + P para abrir o executor de comandos
2. Digite "> Format Document"
